version: '2'
services:

    # nginx container
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./..:/var/www
        ports:
            - "${DOCKER_WEB_PORT}:80"
        links:
            - app

    # php and app container        
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./..:/var/www
        # uncomment whichever service you need and then uncomment it's links
        # links:
            # - database   
            # - cache
        # environment:
        #     - "DB_PORT=3306"
        #     - "DB_HOST=database"
        #     - "REDIS_PORT=6379"
        #     - "REDIS_HOST=cache"

    # database container        
    # database:
    #     image: mysql:5.7
    #     environment:
    #         - "MYSQL_ROOT_PASSWORD=secret"
    #         - "MYSQL_DATABASE=dockerApp"
    #     ports:
    #         - "${DOCKER_DB_PORT:-33060}:3306"

    # cache container
    # cache:
    #     image: redis:3.0
    #     ports:
    #         - "${DOCKER_CACHE_PORT:-63790}:6379"
